### ISSUE TITLE
Rearange Next round and Next Initiative buttons

### ISSUE THREAD

**Issue by powkhenai** [wrycu/paranoia2017#33]
Currently the `Next Initiative` button is at the top of the window and the `Next Round` Button is at the bottom. My brain simply doesn't process this well and I end up accidentally clicking next round before it's time.

I'd like the buttons to both be at the bottom of the initiative window, with the `Next Round` button on the left and the `Next Initiative` button on the right. 

As an additional note here, it would also be helpful if the `Next Round` button simply didn't work as long as the initiative is above 0.

**Comment by wrycu** [comment]
![image](https://github.com/wrycu/paranoia/assets/4709746/3e81636d-810c-4bd7-a714-9f0a2f5be880)

**Comment by wrycu** [comment]
![image](https://github.com/wrycu/paranoia/assets/4709746/baf62e78-76fa-498e-a7ba-0af252ce37d9)
