### ISSUE TITLE
Added Cards get deleted

### ISSUE THREAD

**Issue by kenpoh01** [wrycu/paranoia2017#65]
Hello,
I'm not sure what's happening.  I'm trying to import a .json with cards for the rpg.  This will work, but, as soon as I log out and log back in, the cards get deleted by foundry.  I'm not sure if this is because I created 16 digit ID's for the file I was uploading myself, or if it's the system doing it?
![image](https://github.com/wrycu/paranoia2017/assets/36082436/d222289e-249b-4a79-80fd-9ca09c909c54)

**Comment by wrycu** [comment]
Can you provide the full console log when this happens? (also, how are you importing cards? I don't recall there being any native Foundry functionality for it and I didn't implement anything!)

**Comment by kenpoh01** [comment]
Hopefully you can open this log file.  (Also, I tested importing the card deck in my test world and it works and persists, no problem.)
[kenpohfoundry.ddns.net-1703121824887.log](https://github.com/wrycu/paranoia2017/files/13734034/kenpohfoundry.ddns.net-1703121824887.log)
Here's the text version, in case you can't:
commons.js:15473 Foundry VTT | Foundry Commons Framework Loaded
foundry.js:91804 Foundry VTT | Before DOMContentLoaded
foundry.js:91813 _______________________________________________________________
 _____ ___  _   _ _   _ ____  ______   __ __     _______ _____ 
|  ___/ _ \| | | | \ | |  _ \|  _ \ \ / / \ \   / |_   _|_   _|
| |_ | | | | | | |  \| | | | | |_) \ V /   \ \ / /  | |   | |  
|  _|| |_| | |_| | |\  | |_| |  _ < | |     \ V /   | |   | |  
|_|   \___/ \___/|_| \_|____/|_| \_\|_|      \_/    |_|   |_|  
===============================================================
foundry.js:91823 Foundry VTT | Reestablishing existing session 0925b2336228c1e20149ce01
foundry.js:8536 Foundry VTT | Connected to server socket using session 0925b2336228c1e20149ce01
foundry.js:8632 Foundry VTT | Initializing Foundry Virtual Tabletop Game
foundry.js:3687 Foundry VTT | Synchronized official game time in 3ms
foundry.js:7682 Foundry VTT | Retrieved and compiled template systems/paranoia2017/templates/chat/item.html
foundry.js:7533 Foundry VTT | Loaded localization file systems/paranoia2017/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file lang/en.json
init.js:19 (8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
foundry.js:5802 Foundry VTT | Rendering SceneNavigation
foundry.js:5802 Foundry VTT | Rendering Notifications
foundry.js:5802 Foundry VTT | Rendering Sidebar
foundry.js:5802 Foundry VTT | Rendering PlayerList
foundry.js:5802 Foundry VTT | Rendering Hotbar
foundry.js:5802 Foundry VTT | Rendering Pause
foundry.js:5802 Foundry VTT | Rendering SceneControls
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/hud/toolclip.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/hud/navigation.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/sidebar.html
foundry.js:5802 Foundry VTT | Rendering ChatLog
foundry.js:5802 Foundry VTT | Rendering CombatTracker
foundry.js:5802 Foundry VTT | Rendering Settings
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/user/players.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/hud/hotbar.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/hud/pause.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/hud/controls.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/partials/document-partial.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:5802 Foundry VTT | Rendering ActorDirectory
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/partials/document-partial.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:5802 Foundry VTT | Rendering CardsDirectory
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/partials/pack-partial.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:5802 Foundry VTT | Rendering CompendiumDirectory
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/partials/document-partial.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:5802 Foundry VTT | Rendering ItemDirectory
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/partials/document-partial.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:5802 Foundry VTT | Rendering JournalDirectory
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/partials/playlist-partial.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:5802 Foundry VTT | Rendering PlaylistDirectory
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/scene-partial.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:5802 Foundry VTT | Rendering SceneDirectory
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/partials/document-partial.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:5802 Foundry VTT | Rendering RollTableDirectory
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/chat-log.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/combat-tracker.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/settings.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/document-directory.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/document-directory.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/compendium-directory.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/document-directory.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/document-directory.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/playlists-directory.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/document-directory.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/document-directory.html
foundry.js:73104 Foundry VTT | Fonts loaded and ready.
foundry.js:26758 Foundry VTT | Skipping game canvas - no active scene.
commons.js:8807 Foundry VTT | Deleted Card with id [MwNeSgfrubrZpUFw] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [KIlrPM8mzkl1QjAl] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [aB3cD8eF2gH7iJ1k] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [pQ6rS2tU7vW3xY9z] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [X8yZ0a1B3c2D4e6F] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [gH7i9J5k0L3m2N4o] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [O6pQ3r7S2t4U6v9W] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [wX9y0A1b3C2d4E6f] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [F3g5H7i9J1k6L8n0] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [m2o4P6q8r5S7t9U1] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [V7w0X2y4A5b8C7d9] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [e8F0g2H4i6J9k1L3] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [o9P2q4r6S8t0U1v3] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [y8A2b4C6d8E0f2G4] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [j3k5L7m9N1o2P4q6] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [t3U5v7W9x1Y2a4B6] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [e2F4g6H1i3J5k7L9] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [o4P6q8R5s7T9u1V3] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [V9w1X2y4A6b8C0d2] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [g1H3i5J7k9L1m2N4] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [S3t5U7v9W1x2Y4a6] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [d2E4f6G1h3I5j7K9] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [N4o6P8q2R4s6T8u0] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [X7y9A1b3C5d7E9f0] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [i6J8k0L2m4N6o8P1] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [t7U9v1W3x5Y7a9B1] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [e6F8g0H2i4J6k1L3] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [O9p1Q3r5S7t9U1v3] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [Y9a1B3c5D7e9F0g4] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [j8K0l2Mjn6O8p1Q3] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [t9U1v3W5x7l9a1B3] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [e9F0g2H4i6J8k092] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [o8P1q3R5s7T961V3] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [Y9a1B3c5D7e9g0g2] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [j8K0l2M4v6O8p1Q3] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [t9U1v3W5x7Y9a1a3] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [e9F0g2H4i6J8k0L4] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [o8P1q6R5s7T9u1V3] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [Y9a1B3c5D8e9F0g2] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [j8K0l2M4m6O8p1Q3] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [t9U1v3W5x7Y9a1c3] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [e9F0g2H4i6J8k0L7] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [o8P1q3R5s5T9u1V3] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [Y9a1B3c5D7e9F0g2] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [j8K0l2M4n6O8p1Q3] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [t9U1v3W5x7Y9a1B3] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [e9F0g2H4i6J8k0L2] in parent Cards [7tgRQtQUNC1Ei6BB]
commons.js:8807 Foundry VTT | Deleted Card with id [o8P1q3R5s7T9u1V3] in parent Cards [7tgRQtQUNC1Ei6BB]
foundry.js:5802 Foundry VTT | Rendering CardManager
foundry.js:7682 Foundry VTT | Retrieved and compiled template systems/paranoia2017/templates/cards/manager.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/app-window.html
foundry.js:5802 Foundry VTT | Rendering CardsConfig
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/cards/cards-deck.html

**Comment by kenpoh01** [comment]
Here's a link to a video of the whole process:
https://drive.google.com/file/d/1RccO9XCB4qBccTs-gwaEuadapZV2Bzys/view?usp=drive_link

**Comment by wrycu** [comment]
Thanks for the video! The system is deleting the cards because they don't exist in the world. The way to do this (and I realize it sucks, especially if you've already created cards...) is to create a set of items to represent the cards.

![image](https://github.com/wrycu/paranoia2017/assets/4709746/3ab35a57-ad7a-4f68-809a-d62ac212b216)

The system will then automatically create a "card" entry in the appropriate card stack.

**Comment by wrycu** [comment]
I've updated the wiki to try to make this more clear so hopefully other people don't do the same thing, because I can totally see why you'd think it works that way.
